### ISSUE TITLE
Issue with geodesicRegression function

### ISSUE THREAD

**Issue by amsinha9** [QingyuZhao/Riemannian-rs-fMRI#1]
I am trying to implement your code on some data we have and am running into some issues with geodesicRegression.m. Instead of 3 matrices per subject, I have 6. So the length(X) = 6 where X{i} is a 200x200 covariance matrix. I check for NaNs and Infs in each matrix, however, I get the error:

Error using eig
Input matrix contains NaN or Inf.

Error in expMap (line 15)
[u,G] = eig(tmp);

Error in pdRegression (line 70)
        p = expMap(p,update_p * alpha);

Error in geodesicRegression_ECP (line 70)
    [p,v] = pdRegression(X);

when it gets to the pdRegression function.

Code snippet here:
```
for k = 1:num_controls
    origFilename = control_files(k).name;
    fullFilename = fullfile(control_dir, origFilename);
    fprintf(1, '\nProcessing: %s\n', fullFilename);
    load(fullFilename);
    
    i = 1;
    
    start = start_pt;
    end = end_pt;
    
    while start <= end
%         if start + stride > end
%             start = end;
%         end

        X{i} = cov(datamat(start: end, :));
        
        start = start + stride;
        end = end + stride;

        i = i + 1;  
    
    end
    % check for NaN or inf
    for i = 1:length(X)
        assert(sum(isnan(X{i}(:))) == 0)
        assert(sum(isinf(X{i}(:))) == 0)
        
    end
    
    [p,v] = pdRegression
```

Could you provide some help with this?

**Comment by amsinha9** [comment]
Is this because my matrices are not SPD?

**Comment by QingyuZhao** [comment]
Yes, the X matrices have to be SPD. Most probably it is the operation p^-0.5 that failed.
